twig:
    form_themes: ['widget/fields-block.html.twig']
    default_path: '%kernel.project_dir%/templates'
    globals:
        menu: '@App\Services\Services'
        form: ['widget/fields-block.html.twig']
when@test:
    twig:
        strict_variables: true
